spring:
  data:
    mongodb:
      uri: "mongodb://mongodb/test?serverSelectionTimeoutMS=900"
custom:
  external:
    cron: "* * * ? * *"
    flushCron: "*/5 * * ? * *"
    pageSize: 20
  message:
    connectionUnreachable: "Соединение с базой данных недоступно"
logging:
  level:
    root: ERROR
    org.mongo.timestamp.controller: INFO
    org.mongo.timestamp.config.listener: INFO